proof of concept Rhive patch
Need to resolve this error...

Error: org.apache.hive.service.cli.HiveSQLException: Error while
processing statement: Cannot modify mapred.child.env at runtime. It is
not in list of params that are allowed to be modified at runtime